- hosts: localhost
  connection: local
  become: true # Becoming sudo user here
  tasks:
  - name: 'Install nginx'
    apt:
      name: nginx
      state: present
      update_cache: true
    failed_when: cache_update_time >= 1

  - name: 'Copy nginx file over'
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config
    #when: nginx_config.diff.before.path == nginx_config.diff.after.path
    #failed_when: nginx_config.diff.before.path == nginx_config.diff.after.path
    
  - name: 'Print info from copy task'  
    debug:
      msg: "{{ nginx_config }}"


  - name: 'Restart nginx if needed'
    service: 
      name: nginx
      state: restarted
    when: nginx_config.changed == true
