- hosts: localhost
  connection: local
  become: true # Becoming sudo user here
  tasks:
  - name: 'Uninstall nginx'
    command: apt purge nginx nginx-common nginx-core
    register: purge_output
    changed_when: "'The following packages will be REMOVED' in purge_output.stdout"