- hosts: all
  become: true
  tasks:
  - name: "Restart docker container"
    community.docker.docker_container:
      name: testcontainer
      state: started
      restart: yes
      port:
        - 8090:8090