- hosts: all
  become: true
  tasks:
  - name: "Restart docker container"
    community.docker.docker_container:
      name: testcontainer
      image: nginx
      state: started
      restart: yes 
      ports:
        - 80:80