- hosts: all
  become: true
  tasks:
    - name: "Install required system packages"
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    
    - name: "Add Docker GPG apt key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: "Add Docker Repo"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: "Update apt & install docker-ce"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: "Add docker python module"   # Need this for swarm
      pip:
        name: docker
      
    - name: "Get docker info"
      shell: docker info
      register: docker_info
      changed_when: False

- hosts: manager
  become: true
  tasks: 
    - name: "Create swarm manager"
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: "docker_info.stdout.find('Swarm: inactive') > 0"

    - name: "Get manager ip"
      copy: 
        content: "{{ ansible_default_ipv4.address }}"
        dest: "/tmp/manager-ip"

    - name: "Get manager token"
      shell: docker swarm join-token -q manager
      register: manager_token
    - copy:
        content: "{{ manager_token.stdout }}"
        dest: "/tmp/manager-token"
    
    - name: "Get worker token"
      shell: docker swarm join-token -q worker
      register: worker_token
    - copy:
        content: "{{ worker_token.stdout }}"
        dest: "/tmp/worker-token" 

- hosts: all
  become: true
  tasks: 
    - name: "Join le swarm"
      shell: "docker swarm join --token {{ lookup('file', '/tmp/worker-token') }} {{ lookup('file', '/tmp/manager-ip') }}:2377" # docker swarm uses 2377 for cluster management
      when: "docker_info.stdout.find('Swarm: inactive') > 0"
      retries: 5
      delay: 5
