---
- hosts: all
  become: true
  tasks:
    - name: "Install nginx"
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: "Start nginx service"
      service:
        name: nginx
        state: started
    
    - name: "Add nginx conf"
      template:
        src: "{{ path_to_nginx_conf }}"
        dest: /etc/nginx/nginx.conf

  handlers:
    - name: "Restart nginx"
      service:
        name: nginx
        state: restarted

